server:
  port: 8081

spring:
  kafka:
    bootstrap-servers:
      - 43.201.15.208:9092
      - 43.201.15.208:19092
      - 43.201.15.208:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:emailDB
    driver-class-name: org.h2.Driver
    username: sa
    password: